import type { Analysis, ContributionRules, GitHubIssue, Recommendation, RepoContext, RepoFile } from '../types';
import { stackSkills } from './skills';
const labelWords = ['good first issue','first-timers-only','help wanted','documentation','test','tests','beginner'];
const negativeWords = ['architecture','redesign','refactor','breaking','proposal','discussion','blocked','epic','migration'];
const testPath = /(test|spec|__tests__|tests\/)/i;
const sourcePath = /(src\/|lib\/|app\/|packages\/|cmd\/|internal\/|pkg\/|server\/|client\/)/i;
const age = (date: string) => Math.floor((Date.now() - new Date(date).getTime()) / 86400000);
const words = (issue: GitHubIssue) => `${issue.title} ${issue.body ?? ''} ${issue.labels.map(l => l.name).join(' ')}`.toLowerCase();
function relevantFiles(issue: GitHubIssue, files: RepoFile[]): RepoFile[] { const text = words(issue); const named = files.filter(f => text.includes(f.path.toLowerCase()) || text.includes(f.path.split('/').pop()!.toLowerCase())); const terms = [...text.matchAll(/`([\w./-]+\.(?:ts|tsx|js|py|go|rs|java|md|json|yml|yaml))`/g)].map(x => x[1]); const byTerms = files.filter(f => terms.some(t => f.path.toLowerCase().endsWith(t.toLowerCase()))); const candidates = [...new Map([...named, ...byTerms].map(f => [f.path, f])).values()]; if (candidates.length) return candidates.slice(0, 5); const docs = files.filter(f => (/^docs?\//i.test(f.path) || /\.rst$/i.test(f.path)) && !/\.(png|jpe?g|gif|svg|ico|woff2?)$/i.test(f.path) && !/_static\//i.test(f.path)); if (/\bdocs?|documentation|readme\b/i.test(text) && docs.length) return docs.slice(0, 4); const tests = files.filter(f => testPath.test(f.path)); const src = files.filter(f => sourcePath.test(f.path)); return [...src.slice(0, 2), ...tests.slice(0, 2)].slice(0, 4); }
function recommendation(issue: GitHubIssue, context: RepoContext, skills: string[]): Recommendation { const text = words(issue), labels = issue.labels.map(l => l.name.toLowerCase()); const stack = stackSkills(context.languages, context.files.map(f => f.path)); let score = 0; const reasons: string[] = []; const gaps: string[] = []; const blockers: string[] = [];
  if (labels.some(l => labelWords.some(w => l.includes(w)))) { score += 3; reasons.push(`GitHub labels include ${labels.filter(l => labelWords.some(w => l.includes(w))).slice(0,2).join(' and ')}.`); }
  if (age(issue.updated_at) < 45) { score += 2; reasons.push(`The issue was updated ${age(issue.updated_at)} days ago, suggesting current activity.`); } else { score -= 2; blockers.push(`Last updated ${age(issue.updated_at)} days ago; verify it is still available.`); }
  if (issue.assignees.length) { score -= 3; blockers.push('The issue is already assigned, so another contributor may be working on it.'); }
  if (issue.comments > 18) { score -= 2; blockers.push('A long discussion may indicate unresolved scope or design questions.'); }
  if (/(steps to reproduce|acceptance criteria|expected|actual|reproduce|should)/.test(text)) { score += 2; reasons.push('The description includes concrete problem or acceptance language.'); }
  if (negativeWords.some(w => text.includes(w))) { score -= 3; blockers.push('The wording suggests broader design or migration work.'); }
  const matches = skills.filter(s => text.includes(s) || stack.includes(s)); if (matches.length) { score += Math.min(4, matches.length * 2); reasons.push(`Relevant to your ${matches.slice(0,3).join(', ')} experience.`); }
  const missing = stack.filter(s => ['python','javascript','typescript','java','go','rust','react','node.js','postgresql','redis','async'].includes(s) && !skills.includes(s)); if (missing.length) gaps.push(`The repository uses ${missing.slice(0,2).join(' and ')}, which is not listed in your skills.`);
  const files = relevantFiles(issue, context.files); if (files.some(f => testPath.test(f.path))) { score++; reasons.push('The repository has a nearby test location to inspect.'); }
  const difficulty: Recommendation['difficulty'] = score >= 6 ? 'Low' : score >= 2 ? 'Medium' : 'High'; const fit: Recommendation['fit'] = score >= 7 ? 'Strong fit' : score >= 2 ? 'Reasonable fit' : 'Stretch'; return { issue, score, fit, difficulty, confidence: files.length ? 'Moderate' : 'Limited', reasons, gaps, blockers, relevantFiles: files, concepts: [...new Set([...matches, ...missing.slice(0,2), ...(testPath.test(files.map(f=>f.path).join(' ')) ? ['the project’s test runner'] : [])])].slice(0,4) };
}
function extractRules(content: string): ContributionRules { const lines = content.split(/\r?\n/).map(x => x.replace(/^\s*[-*\d.)]+\s*/, '').trim()).filter(x => x.length > 6 && x.length < 180); const pick = (pattern: RegExp) => lines.filter(l => pattern.test(l)).slice(0, 4); return { setup: pick(/install|setup|environment|dependencies|clone/i), testing: pick(/test|lint|format|check/i), workflow: pick(/branch|pull request|commit|issue|review/i) }; }
export interface AnalysisProvider { analyzeRepository(context: RepoContext, skills: string[]): Analysis; }
export class DeterministicAnalysisProvider implements AnalysisProvider { analyzeRepository(context: RepoContext, skills: string[]): Analysis { const stack = stackSkills(context.languages, context.files.map(f => f.path)); const matches = skills.filter(s => stack.includes(s)); const repoAge = context.recentCommitDate ? age(context.recentCommitDate) : 999; const health = repoAge < 45 ? { label: 'Active' as const, evidence: [`Latest commit was ${repoAge} days ago.`, `${context.issues.length} recently updated open issues were sampled.`] } : repoAge < 180 ? { label: 'Moderate' as const, evidence: [`Latest commit was ${repoAge} days ago.`] } : { label: 'Low' as const, evidence: [`Latest visible commit was ${repoAge} days ago; check activity before investing time.`] }; const recommendations = context.issues.map(i => recommendation(i, context, skills)).sort((a,b) => b.score-a.score).slice(0,5); const fit = matches.length >= 2 ? { label: 'Strong fit' as const, reasons: [`Your skills overlap with the project’s ${matches.join(', ')} stack.`, 'Recommendations favor issues with clear, observable signals.'], gaps: stack.filter(s => !skills.includes(s)).slice(0,2).map(s => `You may encounter ${s}.`) } : matches.length ? { label: 'Reasonable fit' as const, reasons: [`You match ${matches.join(', ')} in the detected stack.`], gaps: stack.filter(s => !skills.includes(s)).slice(0,3).map(s => `The project also uses ${s}.`) } : { label: 'Stretch' as const, reasons: ['No direct stack overlap was identified from the skills you entered.'], gaps: stack.slice(0,3).map(s => `Start by learning the project’s ${s} conventions.`) }; return { context, skills, stack, health, fit, recommendations, rules: extractRules(context.contributing) }; } }
